### ISSUE TITLE
alertmanager with helm kube-prometheus-stack

### ISSUE THREAD

**Issue by Regis-Loyaute** [SriRamanujam/alertmanager-discord-bridge#73]
hello i'm trying to use your discord bridge with a helm kube-prometheus-stack, without success:

here is my alertmanager config, the alertmanager-discord-bridge ip address is http://10.100.1.6:9094

alertmanager:
  fullnameOverride: alertmanager
  enabled: true
  ingress:
    enabled: false
  config:
    global:
      resolve_timeout: 5m
    route:
      group_by: ["alertname"]
      group_wait: 20s
      group_interval: 5m
      repeat_interval: 3h
      receiver: "discord_webhook"
    receivers:
    - name: "discord_webhook"
      webhook_configs:
      - url: "10.100.1.6:9094"

**Comment by SriRamanujam** [comment]
Hi! I can't help debug with just the information you've provided. 

Do you have alerts firing currently that you can use for testing? What logs are printed out? Did you properly configure the Discord webhook? Are you seeing requests come in from Alertmanager?

**Comment by Regis-Loyaute** [comment]
Yes i have alerts that are firing, here are the logs, i using this webhook with other services without issue, yes i'm seeing the requests from alertmanager.

ts=2023-02-13T02:13:41.855Z caller=dispatch.go:352 level=error component=dispatcher msg="Notify for alerts failed" num_alerts=2 err="discord/slack[0]: notify retry canceled due to unrecoverable error after 1 attempts: channel \"\": unexpected status code 400: Json deserialize error: missing field `version` at line 1 column 2189"
ts=2023-02-13T02:15:59.366Z caller=dispatch.go:352 level=error component=dispatcher msg="Notify for alerts failed" num_alerts=1 err="discord/slack[0]: notify retry canceled due to unrecoverable error after 1 attempts: channel \"\": unexpected status code 400: Json deserialize error: missing field `version` at line 1 column 920"
ts=2023-02-13T02:18:41.849Z caller=dispatch.go:352 level=error component=dispatcher msg="Notify for alerts failed" num_alerts=2 err="discord/slack[0]: notify retry canceled due to unrecoverable error after 1 attempts: channel \"\": unexpected status code 400: Json deserialize error: missing field `version` at line 1 column 1838"
ts=2023-02-13T02:18:41.855Z caller=dispatch.go:352 level=error component=dispatcher msg="Notify for alerts failed" num_alerts=2 err="discord/slack[0]: notify retry canceled due to unrecoverable error after 1 attempts: channel \"\": unexpected status code 400: Json deserialize error: missing field `version` at line 1 column 2189"
ts=2023-02-13T02:19:21.429Z caller=dispatch.go:352 level=error component=dispatcher msg="Notify for alerts failed" num_alerts=1 err="discord/slack[0]: notify retry canceled due to unrecoverable error after 1 attempts: channel \"\": unexpected status code 400: Json deserialize error: missing field `version` at line 1 column 1312"
ts=2023-02-13T02:19:21.429Z caller=dispatch.go:352 level=error component=dispatcher msg="Notify for alerts failed" num_alerts=1 err="discord/slack[0]: notify retry canceled due to unrecoverable error after 1 attempts: channel \"\": unexpected status code 400: Json deserialize error: missing field `version` at line 1 column 1050"
ts=2023-02-13T02:23:41.850Z caller=dispatch.go:352 level=error component=dispatcher msg="Notify for alerts failed" num_alerts=2 err="discord/slack[0]: notify retry canceled due to unrecoverable error after 1 attempts: channel \"\": unexpected status code 400: Json deserialize error: missing field `version` at line 1 column 1839"
ts=2023-02-13T02:23:41.855Z caller=dispatch.go:352 level=error component=dispatcher msg="Notify for alerts failed" num_alerts=2 err="discord/slack[0]: notify retry canceled due to unrecoverable error after 1 attempts: channel \"\": unexpected status code 400: Json deserialize error: missing field `version` at line 1 column 2189"
ts=2023-02-13T02:24:21.429Z caller=dispatch.go:352 level=error component=dispatcher msg="Notify for alerts failed" num_alerts=2 err="discord/slack[0]: notify retry canceled due to unrecoverable error after 1 attempts: channel \"\": unexpected status code 400: Json deserialize error: missing field `version` at line 1 column 1924

**Comment by Regis-Loyaute** [comment]
currently trying with this config:

alertmanager:
  fullnameOverride: alertmanager
  enabled: true
  ingress:
    enabled: false
  config:
    global:
      slack_api_url: 
      resolve_timeout: 5m
    receivers:
    - name: "null"
    - name: "discord"
      slack_configs:
      - username: "Prometheus"
        icon_url: https://avatars3.githubusercontent.com/u/3380462        
        send_resolved: true
        title: |-
          [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ if ne .CommonAnnotations.summary ""}}{{ .CommonAnnotations.summary }}{{ else }}{{ .CommonLabels.alertname }}{{ end }}
        text: >-
          {{ range .Alerts -}}
            **Alert:** {{ .Annotations.title }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}
            **Description:** {{ if ne .Annotations.description ""}}{{ .Annotations.description }}{{else}}N/A{{ end }}
            **Details:**
            {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
            {{ end }}
          {{ end }}
    route:
      group_by: ["alertname", "job"]
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 6h
      receiver: "discord"
      routes:
      - receiver: "null"
        match:
          alertname: Watchdog
      - receiver: "discord"
        match_re:
          severity: critical
        continue: true
    inhibit_rules:
    - source_match:
        severity: "critical"
      target_match:
        severity: "warning"
      equal: ["alertname", "namespace"]

**Comment by SriRamanujam** [comment]
Hm. I can't say for sure what's going wrong - it looks like the payload doesn't quite match up. I've never used this with the kube-prometheus-stack deployment, so I can't say for sure without being able to see the json payload. I'll happily accept PRs to improve the flexibility of the parsing code.

Just in case it helps, here's my Alertmanager config:

```
global:
  resolve_timeout: 5m
receivers:
  - name: Discord
    webhook_configs:
      - url: 'http://discord-bridge.monitoring.svc:9094'
route:
  group_by:
    - namespace
  group_interval: 5m
  group_wait: 30s
  receiver: Discord
  repeat_interval: 12h
  routes: []
```

**Comment by Regis-Loyaute** [comment]
Hi, i managed to get it work directly with a discord webhook:

alertmanager:
  # Override the fullname of the Alertmanager
  fullnameOverride: alertmanager
  # Enable the Alertmanager
  enabled: true
  ingress:
    # Disable ingress for the Alertmanager
    enabled: false
  config:
    global:
      # Specify the Slack API URL
      slack_api_url: "https://discord.com/api/webhooks/107624102664231076763986/OOyE-_8pPgwAYT2Pfe3iJHJdhjkGlJ7hI3XedmafgdgdfvcxvcjXA41TV9aViHzQ-KxYc8A/slack"
      # Set the timeout for resolving alerts to 5 minutes
      resolve_timeout: 5m
    receivers:
      - name: "null"
      - name: "discord"
        slack_configs:
          - channel: "k8s"
            # Specify the icon for the alerts
            icon_url: https://avatars3.githubusercontent.com/u/3380462
            # Specify the username for the alerts
            username: "Alerts"
            # Send a notification when the alert is resolved
            send_resolved: true
            # Customize the title for the alerts
            title: '[{{ if eq .Status "firing" }}:fire:{{ else }}:white_check_mark:{{ end }}{{ .Status | toUpper }}{{ if eq .Status "firing" }}:fire:{{ else }}:white_check_mark:{{ end }}] Monitoring Event Notification'
            # Customize the message for the alerts
            text: |-
              {{ range .Alerts }}
              **{{ .Labels.alertname }}**
              {{ if ne .Labels.service "" }}• *Service:* {{ .Labels.service }}
              {{ end }}{{ if ne .Labels.cluster "" }}• *Cluster:* {{ .Labels.cluster }}
              {{ end }}{{ if ne .Labels.instance "" }}• *Instance:* {{ .Labels.instance }}
              {{ end }}• *Severity:* {{ .Labels.severity }}
              {{ if ne .Labels.namespace "" }}• *Namespace:* {{ .Labels.namespace }}
              {{ end }}• *Description:*
              ```
              {{ .Annotations.description }}
              ```
              {{ if ne .Annotations.runbook_url "" }}• *Runbook:* <{{ .Annotations.runbook_url }}|{{ .Annotations.runbook_url }}>
              {{ end }}
              {{ end }}
    route:
      # Group alerts by alertname and job
      group_by: ["alertname", "job"]
      # Wait 30 seconds before grouping alerts
      group_wait: 30s
      # Send a notification every 5 minutes
      group_interval: 5m
      # Repeat notifications every 6 hours
      repeat_interval: 6h
      # Use the "discord" receiver for notifications
      receiver: "discord"
      routes:
        # Send notifications for the "Watchdog" alert to the "null" receiver
        - receiver: "null"
          match:
            alertname: Watchdog
        # Send notifications for alerts with severity "critical" to the "discord" receiver
        - receiver: "discord"
          match_re:
            severity: critical
          # Continue to send notifications for this alert even if it's resolved
          continue: true
      inhibit_rules:
        - source_match:
            severity: "info"
          target_match:
            severity: "warning"
          # Suppress alerts with the same alertname and namespace
          equal:
            - "alertname"
            - "namespace"
            
 Thanks for your help
